### ISSUE TITLE
I have port this repository to nodejs version

### ISSUE THREAD

**Issue by tearsofphoenix** [grocid/libPQP#1]
It takes me couple of days to port your repository to NodeJS version. Here is my [project](https://github.com/tearsofphoenix/node-pqp).
Now, most of tests passed, still have one problem of generate key pairs.

**Comment by grocid** [comment]
Wow, that is very cool! Do you have any benchmarks?

**Comment by grocid** [comment]
```  aes test
    ✓ should aes decrypt

  arithmetic test
<BigNum 17218479456385750618067377696052635483579924745448689921733236816400740691241745619397484537236046173286370919031961587788584927290816661024991609882728717344659503471655990880884679896520055123906467064419056526231345685268240569209892573766037966584735183775739433978714578587782701380797240772477647874555986712746271362892227516205318914435913511141036261376>
    ✓ should compute big number
    ✓ should mul_poly (80ms)
    ✓ should compute square_sparse_poly
    ✓ should compute exp_poly (1101ms)

  keyio test
    ✓ should extract_der_priv_key
    ✓ should extract pub key
    ✓ should extract message
    ✓ should gen private key
    ✓ should gen public key
    ✓ should gen cipher text

  protocol test
    ✓ should decrypt (498ms)
    ✓ should encrypt (535ms)
    ✓ should generate key pairs

  qcmdpc test
    ✓ should syndrome (68ms)
    ✓ should decrypt (381ms)
    ✓ should pack decrypted token (216ms)

  rand test
    ✓ should random vector
    ✓ should flip coin
    ✓ should get weight vector


  20 passing (3s)```

I am getting this, seems all tests are passing fine?

**Comment by grocid** [comment]
The exp_poly operations takes way too long. You are performing FFT inside the while loop, which adds a lot of complexity. Look at https://github.com/grocid/libPQP/blob/master/operations/arithmetic.py

Minor remark: you spelled publick_key.js.

**Comment by tearsofphoenix** [comment]
OK, I'll try to make some enhancement, maybe rewrite core-functions in C.

**Comment by grocid** [comment]
I would not say that time consumption of key generation is any issue here -- it does not matter if it takes 2 or 20 seconds in my opinion, since it is done very rarely.

**Comment by tearsofphoenix** [comment]
Port this to [C version](https://github.com/tearsofphoenix/QuantumNova)
features:

1. add test to cover up to 90% api;
2. no memory leak;
3. simple class inherit architecture;

TODO: 
1. use salsa20 (implemented in libtomcrypt)
2. fix for ASN1 file format.

**Comment by grocid** [comment]
Nice :-) However, I think the JS implementation is the most interesting. Would it be possible to run client-side in browser? Can the key-generation bytecode be turned into asm.js via emscripten?

**Comment by tearsofphoenix** [comment]
I'll try, fft is not so fast in nodejs, it may be very slow in browser even used asm.js. Maybe accelerate
by GPU?

**Comment by grocid** [comment]
Yeah, there is [gpu.js](http://gpu.rocks/). But since the vector length is prime you cannot use standard implementations of FFT, so you would most likely need to implement your own. See e.g. [Raders FFT](https://en.wikipedia.org/wiki/Rader%27s_FFT_algorithm).
